name: publish
on:
  release:
    types: [published]
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: install dependencies
        run: npm ci
      - name: publish to npm
        uses: JS-DevTools/npm-publish@v2.2.1
        with:
          # The NPM access token to use when publishing
          token: ${{secrets.NPM_TOKEN}}
